version: '2.2'

services:
        db:
                image: postgres
        webapp:
                build: .
                command: python manage.py runserver 0.0.0.0:8080
                volumes: 
                - .:/app
                ports: 
                - "127.0.0.1:8080:8080"
                links:
                - db
                depends_on:
                - db
